=== domstolene/ESAS/kontrakter/felles/lukkSak/arbeidsversjon/lukkSak.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://domstol.no/kjennelseBeslutning/arbeidsversjon/kjennelseBeslutning",
  "description": "Skjema som definerer en lukking av sak uten avgjørelse",
  "properties": {
    "forsendelse": {
      "$ref": "#/definitions/forsendelse",
      "description": "Avsender og mottaker"
    },
    "saksInformasjon": {
      "$ref": "#/definitions/saksInformasjon"
    },
    "lukkeKategori": {
      "$ref": "#/definitions/lukkeKategori",
      "description": "Hvorfor saken lukkes"
    },
    "beskrivelse": {
      "type": "string",
      "description": "Fritekst som beskriver hvorfor saken lukkes"
    }
  },
  "required": ["forsendelse", "saksInformasjon", "lukkeKategori"],
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "saksInformasjon": {
      "properties": {
        "saksnummer": {
          "type": "string",
          "description": "Domstolen sitt interne saksnummer. Kan være null dersom sak ikke er opprettet ennå."
        },
        "straffesaksnummer": {
          "$ref": "#/definitions/straffesaksnummer",
          "description": "Politiet sitt interne hovedstraffesaksnummer"
        },
        "kravId": {
          "$ref": "#/definitions/GUID",
          "description": "KravId i nåværende instans. Dersom saken ikke har kravId (f.eks. ved manuell opprettelse), skal ikke lukkSak melding sendes."
        }
      },
      "required": ["straffesaksnummer", "kravId"],
      "type": "object",
      "additionalProperties": false
    },
    "forsendelse": {
      "properties": {
        "meldingsId": {
          "$ref": "#/definitions/GUID"
        },
        "sendtTid": {
          "type": "string",
          "format": "date-time"
        },
        "avsender": {
          "$ref": "#/definitions/avsender"
        },
        "mottaker": {
          "$ref": "#/definitions/mottaker"
        }
      },
      "required": ["meldingsId", "sendtTid", "avsender", "mottaker"],
      "type": "object",
      "additionalProperties": false
    },
    "avsender": {
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        },
        "person": {
          "description": "Person som sender meldingen. Vanligvis dommeren eller saksbehandleren",
          "$ref": "#/definitions/ansattPerson"
        }
      },
      "required": ["organisasjon"],
      "type": "object",
      "additionalProperties": false
    },
    "mottaker": {
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        }
      },
      "required": ["organisasjon"],
      "type": "object",
      "additionalProperties": false
    },
    "organisasjon": {
      "description": "Entydig identifikator av juridisk enhet. F.eks et spesifikt domstol embete eller politidistrikt",
      "properties": {
        "navn": {
          "type": "string",
          "description": "F.eks. Nordland politidistrikt eller Oslo tingrett."
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        }
      },
      "required": ["organisasjonsnummer"],
      "type": "object",
      "additionalProperties": false
    },
    "ansattPerson": {
      "description": "Type for personer som er ansatt hos påtale eller domstolen(saksbehandlere, påtaleadvokater, statsadvokater,...)",
      "properties": {
        "etternavn": {
          "type": "string"
        },
        "fornavn": {
          "type": "string"
        },
        "tittel": {
          "type": "string"
        }
      },
      "required": ["etternavn", "fornavn", "tittel"],
      "type": "object",
      "additionalProperties": false
    },
    "lukkeKategori": {
      "description": "Kategori for hvorfor saken lukkes",
      "enum": ["DUPLIKAT", "FEIL", "ANNET"],
      "type": "string"
    },
    "organisasjonsnummer": {
      "type": "string",
      "description": "Norsk organisasjonsnummer fra BRREG. Referanse til politistrikt, domstol, fengsel. https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/",
      "pattern": "^[0-9]+$",
      "minLength": 9,
      "maxLength": 9
    },
    "straffesaksnummer": {
      "type": "string",
      "description": "Som regel et løpenummer, men kan i fremtiden også inneholde bokstaver",
      "minLength": 3,
      "maxLength": 30
    },
    "GUID": {
      "type": "string",
      "format": "uuid"
    }
  }
}

=== domstolene/ESAS/kontrakter/felles/lukkSak/1.0/eksempelfiler/lukkSak-eksempel-1.json
{
  "forsendelse": {
    "meldingsId": "2CB6929E-DE3F-49A4-8AE3-9625640DF0AA",
    "sendtTid": "2022-07-06T16:35:00+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "826726342",
        "navn": "Buskerud tingrett"
      },
      "person": {
        "etternavn": "Saksbehandler",
        "fornavn": "Litt",
        "tittel": "Saksbehandler"
      }
    },
    "mottaker": {
      "organisasjon": {
        "organisasjonsnummer": "983997953",
        "navn": "Innlandet politidistrikt"
      }
    }
  },
  "lukkeKategori": "DUPLIKAT",
  "beskrivelse": "Lukker denne saken da vi mottok to begjæringer på samme sak fra politiet",
  "saksInformasjon": {
    "saksnummer": "22-025462ENE-TBUS/TDRA",
    "straffesaksnummer": "15434820",
    "kravId": "16972F79-0A35-4EC7-90A1-81E4EFAE1EAA"
  }
}
