=== domstolene/ESAS/kontrakter/varetekt/tilbudVaretektsplass/1.0/tilbudVaretektsplass.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kriminalomsorgen.no/varetekt/1.0/tilbudVaretektsplass",
  "description": "Tilbud om varetektsplass fra Kriminalomsorgen til påtale.",
  "type": "object",
  "properties": {
    "forsendelse": {
      "$ref": "#/definitions/forsendelse",
      "description": "avsender og mottaker"
    },
    "hovedStraffesaksnummer": {
      "$ref": "#/definitions/straffesaksnummer",
      "description": "Hovedsaken i et sakskompleks, også saksbehandlersak."
    },
    "tilbudVaretektsplassId": {
      "$ref": "#/definitions/unikId",
      "description": "ID på plasstilbudet. Alle svar på tilbudet skal koble til denne nøkkelen."
    },
    "anmodningsId": {
      "$ref": "#/definitions/unikId",
      "description": "Unik nøkkel på bestillingen, brukes til å koble svar fra KO, siktelse og helse og risiko."
    },
    "fengselDerPlassTilbys": { "$ref": "#/definitions/organisasjon" },
    "fengseletsTelefonnummer": {
      "$ref": "#/definitions/kontorOgVaktTlf",
      "description": "Eventuelle telefonnummer til fengslet. De oppgis slik at politiet kan spare tid om man må kontakte fengsel for koordinering eller hendelseshåndtering."
    },
    "kommentarTilPlasstilbudet": {
      "type": "string",
      "description": "Utfyllende informasjon om tilbudet, hvis nødvendig. Kan brukes til å oppgi direkte telefonnummer i første versjoner og spesielle tilfeller m.m."
    },
    "varetektsplassTilbysFra": {
      "$ref": "#/definitions/datoTid",
      "description": "Plassen tilbys normalt fra når tilbudet blir sendt. Plass kan tilbys eksempelvis fra dagen etter i enkelte tilfeller og ved spesielle forespørsler."
    }
  },
  "required": [
    "forsendelse",
    "hovedStraffesaksnummer",
    "anmodningsId",
    "tilbudVaretektsplassId",
    "fengselDerPlassTilbys",
    "varetektsplassTilbysFra"
  ],
  "additionalProperties": false,

  "definitions": {
    "kontorOgVaktTlf": {
      "type": "object",
      "properties": {
        "kontortid": {
          "$ref": "#/definitions/telefonnummer",
          "description": "Telefonnummer til anstalt på dagtid."
        },
        "vakt": {
          "$ref": "#/definitions/telefonnummer",
          "description": "Telefonnummer til kvelds- og helgevakt."
        }
      }
    },
    "ansattPerson": {
      "type": "object",
      "description": "Saksbehandler, jurist etterforsker hos politiet, ansatte hos domstolene eller kriminalomsorgen",
      "properties": {
        "tittel": {
          "type": "string"
        },
        "navn": {
          "$ref": "#/definitions/personnavn"
        },
        "kontakt": {
          "$ref": "#/definitions/kontaktInfoPerson",
          "description": "Minimum epost adresse til den som sender melding."
        }
      },
      "required": ["navn", "kontakt"],
      "additionalProperties": false
    },
    "personnavn": {
      "type": "object",
      "properties": {
        "fornavn": {
          "type": "string"
        },
        "mellomnavn": {
          "type": "string"
        },
        "etternavn": {
          "type": "string"
        }
      },
      "required": ["fornavn", "etternavn"],
      "additionalProperties": false
    },
    "kontaktInfoPerson": {
      "type": "object",
      "description": "Alle har epost adresse, men kanskje ikke registrert mobil/telefon",
      "properties": {
        "epost": {
          "$ref": "#/definitions/epost"
        },
        "telefonnummer": {
          "$ref": "#/definitions/telefonnummer"
        }
      },
      "required": ["epost"],
      "additionalProperties": false
    },
    "avsender": {
      "type": "object",
      "properties": {
        "organisasjon": {
          "$ref": "#/definitions/organisasjon"
        },
        "person": {
          "$ref": "#/definitions/ansattPerson",
          "description": "Person som trykker på send til påtale."
        }
      },
      "required": ["organisasjon"],
      "additionalProperties": false
    },
    "kontaktInfo": {
      "type": "object",
      "properties": {
        "epost": {
          "type": "string"
        },
        "telefonnummer": {
          "type": "array",
          "items": { "$ref": "#/definitions/telefonnummer" }
        }
      },
      "required": ["telefonnummer"],
      "additionalProperties": false
    },
    "forsendelse": {
      "type": "object",
      "description": "Sender (kriminalomsorg) og mottaker (påtale) av meldingen",
      "properties": {
        "meldingsId": {
          "$ref": "#/definitions/unikId",
          "description": "Unik ID for denne meldingen, hvis plasstilbud blir sendt på nytt vil det være ny meldingsId"
        },
        "sendtTid": {
          "$ref": "#/definitions/datoTid"
        },
        "avsender": {
          "$ref": "#/definitions/avsender"
        },
        "mottakerOrganisasjon": {
          "$ref": "#/definitions/organisasjon",
          "description": "Bestillende politidistrikt."
        }
      },
      "required": [
        "meldingsId",
        "avsender",
        "mottakerOrganisasjon",
        "sendtTid"
      ],
      "additionalProperties": false
    },
    "organisasjon": {
      "description": "Entydig identifikator av juridisk enhet. F.eks en spesifik domstol, embete eller politidistrikt",
      "type": "object",
      "properties": {
        "navn": {
          "description": "F.eks. Oslo politidistikt, Riksadvokaten, Borgarting lagmannsrett",
          "type": "string"
        },
        "organisasjonsnummer": {
          "$ref": "#/definitions/organisasjonsnummer"
        }
      },
      "required": ["organisasjonsnummer", "navn"],
      "additionalProperties": false
    },
    "personnavn": {
      "type": "object",
      "properties": {
        "fornavn": { "type": "string" },
        "mellomnavn": { "type": "string" },
        "etternavn": { "type": "string" }
      },
      "required": ["etternavn"],
      "additionalProperties": false
    },
    "organisasjonsnummer": {
      "type": "string",
      "description": "Norsk organisasjonsnummer fra BRREG. Referanse til politistrikt, domstol, fengsel. https://www.brreg.no/om-oss/registrene-vare/om-enhetsregisteret/organisasjonsnummeret/",
      "pattern": "[0-9]+",
      "minLength": 9,
      "maxLength": 9
    },
    "epost": {
      "type": "string",
      "format": "email"
    },
    "straffesaksnummer": {
      "type": "string",
      "description": "Som regel et løpenummer, men kan i fremtiden også inneholde bokstaver",
      "minLength": 3,
      "maxLength": 30
    },
    "telefonnummer": {
      "type": "string",
      "description": "Ett telefonnummer, norsk eller utenlands, med eller uten land prefix",
      "maxLength": 30,
      "minLength": 1
    },
    "unikId": {
      "type": "string",
      "description": "GUID eller andre unike id'er. Trenger ikke være global unik.",
      "maxLength": 40,
      "minLength": 1
    },
    "datoTid": {
      "type": "string",
      "format": "date-time"
    }
  }
}

=== domstolene/ESAS/kontrakter/varetekt/tilbudVaretektsplass/1.0/eksempelfiler/tilbudVaretektsplass-eksempel-1.json
{
  "forsendelse": {
    "meldingsId": "C5E8E429-2B8E-48A9-A9D3-FDAA5F9BEZ",
    "sendtTid": "2022-11-03T10:19:55+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "911830868",
        "navn": "Kriminalomsorgsdirektoratet"
      },
      "person": {
        "navn": {
          "etternavn": "Årdal",
          "fornavn": "Jo"
        },
        "kontakt": { "epost": "en.bruker@kriminalomsorg.no" }
      }
    },
    "mottakerOrganisasjon": {
      "organisasjonsnummer": "983997953",
      "navn": "Innlandet politidistrikt"
    }
  },
  "tilbudVaretektsplassId": "b04782d3-502e-43d8-8c45-7e84d279d33a",
  "hovedStraffesaksnummer": "15434811",
  "anmodningsId": "D784D27C-C1BB-4BB2-90FD-96C414A64AE1",
  "fengselDerPlassTilbys": {
    "organisasjonsnummer": "890286712",
    "navn": "Bjørgvin fengsel"
  },
  "varetektsplassTilbysFra": "2023-11-04T10:00:00+02:00"
}

=== domstolene/ESAS/kontrakter/varetekt/tilbudVaretektsplass/1.0/eksempelfiler/tilbudVaretektsplass-eksempel-2.json
{
  "forsendelse": {
    "meldingsId": "C5E8E429-2B8E-48A9-A9D3-FDAA5F9BEZ",
    "sendtTid": "2023-11-03T10:19:55+02:00",
    "avsender": {
      "organisasjon": {
        "organisasjonsnummer": "911830868",
        "navn": "Kriminalomsorgsdirektoratet"
      },
      "person": {
        "navn": {
          "etternavn": "Årdal",
          "fornavn": "Jo"
        },
        "kontakt": { "epost": "en.bruker@kriminalomsorg.no" }
      }
    },
    "mottakerOrganisasjon": {
      "organisasjonsnummer": "982531950",
      "navn": "Politidirektoratet"
    }
  },
  "tilbudVaretektsplassId": "b04782d3-502e-43d8-8c45-7e84d279d33a",
  "hovedStraffesaksnummer": "15434811",
  "anmodningsId": "D784D27C-C1BB-4BB2-90FD-96C414A64AE1",
  "fengselDerPlassTilbys": {
    "organisasjonsnummer": "890286712",
    "navn": "Bjørgvin fengsel"
  },
  "fengseletsTelefonnummer": {
    "kontortid": "11 22 11 22",
    "vakt": "11 33 11 33"
  },
  "kommentarTilPlasstilbudet": "OBS: fengselet stenger om 2 uker for 4 måneders vedlikehold av bygningsmassen.",
  "varetektsplassTilbysFra": "2023-11-04T10:00:00+02:00"
}
