=== domstolene/ESAS/kontrakter/politi/fengsling/0.9/innsettelsesordre.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$ref": "#/$defs/innsettelsesordreType",
  "$defs": {
    "beslutningType": {
      "title": "beslutning",
      "type": "object",
      "required": ["besluttetAv", "tidspunkt"],
      "additionalProperties": false,
      "properties": {
        "besluttetAv": {
          "type": "string"
        },
        "tidspunkt": {
          "type": "string",
          "format": "date-time"
        },
        "restriksjoner": {
          "type": "array",
          "title": "restriksjoner",
          "items": {
            "type": "object",
            "required": ["kode", "lovreferanse"],
            "additionalProperties": false,
            "properties": {
              "kode": { "type": "string" },
              "lovreferanse": { "type": "string" },
              "startDato": { "type": "string", "format": "date" },
              "sluttDato": { "type": "string", "format": "date" }
            }
          }
        },
        "merknad": {
          "type": "string"
        }
      }
    },
    "kodeverkType": {
      "type": "object",
      "required": ["navn"],
      "additionalProperties": false,
      "properties": {
        "kode": {
          "type": "string"
        },
        "navn": {
          "type": "string"
        }
      }
    },
    "personFullType": {
      "type": "object",
      "required": ["internId", "rolle", "navn", "kjoenn", "foedselsdato"],
      "additionalProperties": false,
      "properties": {
        "internId": {
          "type": "number"
        },
        "rolle": {
          "$ref": "#/$defs/kodeverkType"
        },
        "navn": {
          "title": "navn",
          "type": "object",
          "required": ["fornavn", "etternavn"],
          "additionalProperties": false,
          "properties": {
            "fornavn": {
              "type": "string"
            },
            "etternavn": {
              "type": "string"
            }
          }
        },
        "foedselsnummer": {
          "type": "array",
          "description": "flere fødselsnummer mulig senere",
          "items": { "type": "string" }
        },
        "dNummer": {
          "type": "string"
        },
        "sspNummer": {
          "type": "string"
        },
        "kjoenn": {
          "type": "string"
        },
        "foedselsdato": {
          "type": "string"
        },
        "adresse": {
          "type": "string"
        },
        "telefonnumer": {
          "type": "string"
        },
        "statsborgerskap": {
          "type": "array",
          "title": "statsborgerskap",
          "items": {
            "$ref": "#/$defs/kodeverkType"
          }
        },
        "verge": {
          "type": "string"
        },
        "forsvarer": {
          "type": "string"
        }
      }
    },
    "personEnkelType": {
      "type": "object",
      "required": ["internId", "rolle", "navn"],
      "additionalProperties": false,
      "properties": {
        "internId": {
          "type": "number"
        },
        "rolle": {
          "$ref": "#/$defs/kodeverkType"
        },
        "navn": {
          "title": "navn",
          "type": "object",
          "required": ["fornavn", "etternavn"],
          "additionalProperties": false,
          "properties": {
            "fornavn": {
              "type": "string"
            },
            "etternavn": {
              "type": "string"
            }
          }
        },
        "kjoenn": {
          "type": "string"
        },
        "foedselsdato": {
          "type": "string"
        },
        "statsborgerskap": {
          "type": "array",
          "title": "statsborgerskap",
          "items": {
            "$ref": "#/$defs/kodeverkType"
          }
        }
      }
    },
    "adresseType": {
      "title": "adresse",
      "type": "object",
      "required": ["adresseLinjer", "postnummer", "poststed", "land"],
      "additionalProperties": false,
      "properties": {
        "adresseLinjer": {
          "type": "array",
          "title": "adresseLinjer",
          "items": {
            "type": "string"
          }
        },
        "postnummer": {
          "type": "string"
        },
        "poststed": {
          "type": "string"
        },
        "land": {
          "$ref": "#/$defs/kodeverkType"
        }
      }
    },
    "hendelseType": {
      "title": "hendelse",
      "type": "object",
      "required": [
        "gjerningstidspunktFra",
        "gjerningstidspunktTil",
        "gjerningssted"
      ],
      "additionalProperties": false,
      "properties": {
        "gjerningstidspunktFra": {
          "type": "string",
          "format": "date-time"
        },
        "gjerningstidspunktTil": {
          "type": "string",
          "format": "date-time"
        },
        "gjerningssted": {
          "$ref": "#/$defs/adresseType"
        }
      }
    },
    "straffesakType": {
      "title": "straffesak",
      "type": "object",
      "required": [
        "straffesaksnummer",
        "hendelse",
        "statistikkgruppe",
        "krimtype"
      ],
      "additionalProperties": false,
      "properties": {
        "straffesaksnummer": {
          "type": "string"
        },
        "hendelse": {
          "$ref": "#/$defs/hendelseType"
        },
        "statistikkgruppe": {
          "$ref": "#/$defs/kodeverkType"
        },
        "krimtype": {
          "$ref": "#/$defs/kodeverkType"
        },
        "prinsipalLovbud": {
          "title": "prinsipalLovbud",
          "type": "object",
          "required": ["lovreferanse", "gjengivelse"],
          "additionalProperties": false,
          "properties": {
            "lovbudId": {
              "type": "string"
            },
            "lovreferanse": {
              "type": "string"
            },
            "gjengivelse": {
              "type": "string"
            },
            "grunnlagstekst": {
              "type": "string"
            },
            "strafferamme": {
              "description": "antall måneder",
              "type": "number"
            }
          }
        },
        "involverte": {
          "title": "involverte",
          "description": "Siktede, domfelte, vitner og fornærmet i straffesaken",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "medsiktede": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/personFullType"
              }
            },
            "vitner": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/personEnkelType"
              }
            },
            "fornaermede": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/personEnkelType"
              }
            }
          }
        }
      }
    },
    "personVaretektInfoType": {
      "title": "personVaretektInfo",
      "type": "object",
      "required": ["personVaretekt", "straffesaker"],
      "additionalProperties": false,
      "properties": {
        "personVaretekt": {
          "$ref": "#/$defs/personFullType"
        },
        "helseopplysninger": {
          "type": "string"
        },
        "straffesaker": {
          "type": "array",
          "title": "straffesaker",
          "items": {
            "$ref": "#/$defs/straffesakType"
          }
        }
      }
    },
    "orgenhetType": {
      "title": "organisasjonsnummer",
      "type": "object",
      "required": ["orgnr"],
      "additionalProperties": false,
      "properties": {
        "orgnr": {
          "type": "string"
        },
        "navn": {
          "type": "string"
        }
      }
    },
    "avsenderInfoType": {
      "title": "avsenderinformasjon",
      "type": "object",
      "required": ["orgenhet", "saksbehandler"],
      "additionalProperties": false,
      "properties": {
        "orgenhet": {
          "$ref": "#/$defs/orgenhetType"
        },
        "saksbehandler": {
          "type": "object",
          "required": ["navn"],
          "additionalProperties": false,
          "properties": {
            "brukeridentifikasjon": { "type": "string" },
            "navn": { "type": "string" }
          }
        }
      }
    },
    "innsettelsesordreType": {
      "description": "JSON Schema generated by XMLSpy v2022 rel. 2 (x64) (http://www.altova.com)",
      "type": "object",
      "required": [
        "forsendelse",
        "hovedStraffesaksnummer",
        "kontaktPersonKDI",
        "varetektSyklusId",
        "kravId",
        "beslutning",
        "paagrepetTidspunkt",
        "personVaretektInfo"
      ],
      "additionalProperties": false,
      "properties": {
        "forsendelse": {
          "title": "forsendelse",
          "type": "object",
          "required": ["meldingsId", "avsender", "mottaker"],
          "additionalProperties": false,
          "properties": {
            "meldingsId": {
              "type": "string"
            },

            "avsender": {
              "$ref": "#/$defs/avsenderInfoType"
            },
            "mottaker": {
              "type": "object",
              "required": ["orgnr"],
              "additionalProperties": false,
              "properties": {
                "orgnr": { "type": "string" },
                "navn": { "type": "string" }
              }
            }
          }
        },
        "hovedStraffesaksnummer": { "type": "string" },
        "kontaktPersonKDI": {
          "$ref": "#/$defs/kodeverkType"
        },
        "varetektSyklusId": {
          "type": "string"
        },
        "kravId": {
          "type": "string"
        },
        "beslutning": {
          "$ref": "#/$defs/beslutningType"
        },
        "paagrepetTidspunkt": {
          "type": "string",
          "format": "date-time"
        },
        "personVaretektInfo": {
          "$ref": "#/$defs/personVaretektInfoType"
        },
        "paategningsdokumentRef": {
          "type": "string"
        },
        "dokumenter": {
          "type": "string"
        }
      }
    }
  }
}

=== domstolene/ESAS/kontrakter/politi/fengsling/0.9/innsettelsesordre.json
{
  "forsendelse": {
    "meldingsId": "{16EB61D8-65A6-48A7-A393-AF1A872E3FC7}",
    "avsender": {
      "orgenhet": {
        "orgnr": "1235111",
        "navn": "Innlandet politidistrikt"
      },
      "saksbehandler": {
        "brukeridentifikasjon": "bes005",
        "navn": "Bjørn Erik .. struktur med navn.."
      }
    },
    "mottaker": {
      "orgnr": "345234",
      "navn": "Oslo tingrett"
    }
  },
  "hovedStraffesaksnummer": "15434819",
  "kontaktPersonKDI": {
    "navn": "navn og bid Jo Å"
  },
  "varetektSyklusId": "{4CB21DFF-A651-4919-A2AF-EDA7D985C941}",
  "kravId": "unik id {9CEF9D44-684A-49DB-9366-49221603E6AB}",
  "beslutning": {
    "besluttetAv": "jurist som beslutter",
    "tidspunkt": "2022-06-02T08:47:21",
    "restriksjoner": [
      {
        "kode": "brev_besoek_forbud",
        "lovreferanse": "§ 186, 2.ledd 1.pkt. - Brev og besøksforbud"
      },
      {
        "kode": "full_isolasjon",
        "lovreferanse": "§ 186a - Fullstendig isolasjon"
      }],
    "merknad": "Hvilke varianter av brev og besøksforbud og delvs/full isolasjon er mulig.\r\nHva med annet, hvilken lovhjemmel er det og hva kan det være. Det er ikke mulig strukturert i dag"
  },
  "paagrepetTidspunkt": "2022-06-02T08:47:21",
  "personVaretektInfo": {
    "personVaretekt": {
      "internId": 700892414,
      "rolle": {
        "kode": "SIKT",
        "navn": "Siktet"
      },
      "navn": {
        "fornavn": "Morsom",
        "etternavn": "KIWI"
      },
      "foedselsnummer": ["14846399381"],
      "sspNummer": "1 hvis den finnes",
      "kjoenn": "M",
      "foedselsdato": "1963-04-14",
      "adresse": "adresselinjer er denne nødvendig?",
      "telefonnumer": " liste er denne nødvendig?",
      "statsborgerskap": [
        {
          "kode": "NOR",
          "navn": "Norge"
        }],
      "verge": "person hvis det er aktuelt",
      "forsvarer": "forsvarerinformasjon hvis den finnes"
    },
    "helseopplysninger": "syk mann",
    "straffesaker": [
      {
        "straffesaksnummer": "15434819",
        "hendelse": {
          "gjerningstidspunktFra": "2022-01-01T00:00:00",
          "gjerningstidspunktTil": "2022-01-01T00:00:00",
          "gjerningssted": {
            "adresseLinjer": ["Waldemar Carlsens veg 4"],
            "postnummer": "2214",
            "poststed": "KONGSVINGER",
            "land": {
              "kode": "NOR",
              "navn": "Norge"
            }
          }
        },
        "statistikkgruppe": {
          "kode": "1770",
          "navn": "Grov mishandling i nære relasjoner, med kroppskrenkelse"
        },
        "krimtype": {
          "kode": "03",
          "navn": "Vold"
        },
        "prinsipalLovbud": {
          "lovbudId": "{257EDDBA-D2B2-40A5-984E-624F8222EBCA}",
          "lovreferanse": "Straffeloven § 283, jf. § 282",
          "grunnlagstekst": "Lørdag 1. januar 2022 kl. 00.00 i Waldemar Carlsens veg 4 i Kongsvinger tok Morsom Kiwi og Masse Kiwi og grisebanket dama til Morsom Kiwi Sannferdig Kos. Sannferdig Kos fikk fire knekte ribbeing, knust nese og knekt fot.",
          "gjengivelse": "for grovt ved trusler, tvang, frihetsberøvelse, vold eller andre krenkelser, alvorlig eller gjentatt å ha mishandlet\r\n\r\na) sin nåværende eller tidligere ektefelle eller samboer, \r\n\r\nMishandlingen er grov fordi det særlig legges vekt på at den har hatt til følge betydelig skade eller død, og for øvrig\r\n\r\na) dens varighet,",
          "strafferamme": 180
        },
        "involverte": {
          "medsiktede": [
            {
              "internId": 700892415,
              "rolle": {
                "kode": "SIKT",
                "navn": "Siktet"
              },
              "navn": {
                "fornavn": "Masse",
                "etternavn": "KIWI"
              },
              "foedselsnummer": ["19877099302"],
              "sspNummer": "1 hvis den finnes",
              "kjoenn": "M",
              "foedselsdato": "1970-07-19",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }]
            }],
          "fornaermede": [
            {
              "internId": 700892735,
              "rolle": {
                "kode": "FORN",
                "navn": "Fornærmet"
              },
              "navn": {
                "fornavn": "Sannferdig",
                "etternavn": "KOS"
              },
              "kjoenn": "K",
              "foedselsdato": "1974-10-31",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }]
            }]
        }
      },
      {
        "straffesaksnummer": "15434820",
        "hendelse": {
          "gjerningstidspunktFra": "2022-03-01T00:00:00",
          "gjerningstidspunktTil": "2022-03-01T00:00:00",
          "gjerningssted": {
            "adresseLinjer": ["Loftsgårdsvegen 5"],
            "postnummer": "2670",
            "poststed": "OTTA",
            "land": {
              "kode": "NOR",
              "navn": "Norge"
            }
          }
        },
        "statistikkgruppe": {
          "kode": "0753",
          "navn": "Grov narkotikaovertredelse, betydelig mengde"
        },
        "krimtype": {
          "kode": "05",
          "navn": "Narkotika"
        },
        "prinsipalLovbud": {
          "lovbudId": "{0B0D6AED-3A43-4B70-AD86-8A4FE38B090B}",
          "lovreferanse": "Straffeloven § 232 annet ledd første straffalternativ, jf. § 231 første ledd, jf. straffeloven § 27",
          "grunnlagstekst": "Campingbil med kokeutstyr og Breaking Bad DVD'er",
          "gjengivelse": "for ulovlig å ha tilvirket, innført, utført, ervervet, oppbevart, sendt eller overdratt narkotika. \r\n\r\nOvertredelsen omfatter en meget betydelig mengde.\r\n\r\nNår et straffebud er overtrådt av noen som har handlet på vegne av et foretak, kan foretaket straffes.",
          "strafferamme": 180
        },
        "involverte": {
          "medsiktede": [
            {
              "internId": 700892415,
              "rolle": {
                "kode": "SIKT",
                "navn": "Siktet"
              },
              "navn": {
                "fornavn": "Masse",
                "etternavn": "KIWI"
              },
              "foedselsnummer": ["19877099302"],
              "sspNummer": "1 hvis den finnes",
              "kjoenn": "M",
              "foedselsdato": "1970-07-19",
              "statsborgerskap": [
                {
                  "kode": "NOR",
                  "navn": "Norge"
                }]
            }],
          "vitner": [
            {
              "internId": 700892688,
              "rolle": {
                "kode": "VITN",
                "navn": "Vitne"
              },
              "navn": {
                "fornavn": "Ariane",
                "etternavn": "HUFSETE"
              },
              "kjoenn": "K",
              "foedselsdato": "1970-01-01",
              "statsborgerskap": [
                {
                  "kode": "ARM",
                  "navn": "Armenia"
                }]
            }]
        }
      },
      {
        "straffesaksnummer": "15434821",
        "hendelse": {
          "gjerningstidspunktFra": "2022-04-05T00:00:00",
          "gjerningstidspunktTil": "2022-04-05T00:00:00",
          "gjerningssted": {
            "adresseLinjer": ["Rabben 9"],
            "postnummer": "2611",
            "poststed": "LILLEHAMMER",
            "land": {
              "kode": "NOR",
              "navn": "Norge"
            }
          }
        },
        "statistikkgruppe": {
          "kode": "1754",
          "navn": "Kroppsskade"
        },
        "krimtype": {
          "kode": "03",
          "navn": "Vold"
        },
        "prinsipalLovbud": {
          "lovbudId": "{664DC73B-828D-4196-9D94-5EB1D1811A9B}",
          "lovreferanse": "Straffeloven § 273",
          "grunnlagstekst": "Lormen Quatro ble lappet til av Morsom Kiwi så han blødde neseblod.",
          "gjengivelse": "for å ha skadet en annens kropp eller helse, gjort en annen fysisk maktesløs eller fremkalt bevisstløshet eller liknende tilstand hos en annen.",
          "strafferamme": 72
        },
        "involverte": {
          "fornaermede": [
            {
              "internId": 700892547,
              "rolle": {
                "kode": "FORN",
                "navn": "Fornærmet"
              },
              "navn": {
                "fornavn": "Lormen",
                "etternavn": "QUATRO"
              },
              "kjoenn": "M",
              "foedselsdato": "1978-01-12",
              "statsborgerskap": [
                {
                  "kode": "ITA",
                  "navn": "Italia"
                }]
            }]
        }
      },
      {
        "straffesaksnummer": "15434850",
        "hendelse": {
          "gjerningstidspunktFra": "2015-01-01T00:00:00",
          "gjerningstidspunktTil": "2015-11-01T00:00:00",
          "gjerningssted": {
            "adresseLinjer": ["Walmannsvegen 81"],
            "postnummer": "2230",
            "poststed": "SKOTTERUD",
            "land": {
              "kode": "NOR",
              "navn": "Norge"
            }
          }
        },
        "statistikkgruppe": {
          "kode": "1604",
          "navn": "Trusler, skytevåpen (§ 227)"
        },
        "krimtype": {
          "kode": "03",
          "navn": "Vold"
        },
        "prinsipalLovbud": {
          "lovbudId": "{1713FA29-4E82-7F97-E053-0B3EA30AAE0D}",
          "lovreferanse": "Straffeloven (1902) § 227 første straffalternativ",
          "grunnlagstekst": "Torsdag 1. januar 2015 kl. 00.00 i Walmannsvegen 81 i Eidskog truet Morsom Kiwi fornærmede med en avsaget hagle.",
