=== domstolene/ESAS/kontrakter/rusproeve/resultatRusproeve/1.0/resultatRusproeve.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://kriminalomsorg.no/kriminalomsorg/1.0/resultatRusproeve",
  "description": "Analyse av rusprøve for oversendelse Kriminalomsorgen. Schema versjon 2020-12",
  "type": "object",
  "properties": {
    "sendtTid": {
      "type": "string",
      "format": "date-time"
    },
    "meldingsId": {
      "$ref": "#/definitions/unikId",
      "description": "Unik ID for denne meldingen, hvis resultatet blir sendt på nytt vil det være ny meldingsId."
    },
    "rekvisisjonsId": {
      "$ref": "#/definitions/unikId",
      "description": "Unik ID på rekvisisjonen fra Kriminalomsorgen som resultatet er knyttet til."
    },
    "saksId": {
      "type": "string",
      "description": "OUS sin id på analysert prøvesett."
    },
    "fortolkningstekst": {
      "type": "string",
      "description": "Fortolkningstekst for resultatet."
    },
    "sakskommentar": {
      "type": "string",
      "description": "Valgfri kommentar til saken."
    },
    "analyseresultater": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/analyseresultat"
      },
      "description": "Liste over analyseresultater."
    }
  },
  "required": [
    "sendtTid",
    "meldingsId",
    "rekvisisjonsId",
    "saksId",
    "fortolkningstekst",
    "analyseresultater"
  ],
  "additionalProperties": false,
  "definitions": {
    "analyseresultat": {
      "type": "object",
      "properties": {
        "typeAnalyse": { "type": "string" },
        "erPaavist": { "type": "boolean" },
        "erAkkreditertMetode": { "type": "boolean" }
      },
      "required": ["typeAnalyse", "erPaavist", "erAkkreditertMetode"]
    },
    "unikId": {
      "type": "string",
      "minLength": 1,
      "maxLength": 40,
      "description": "Representerer en unik identifikator (GUID)."
    }
  }
}

=== domstolene/ESAS/kontrakter/rusproeve/resultatRusproeve/1.0/eksempelfiler/resultatRusproeve-eksempel-1.json
{
  "sendtTid": "2022-11-03T10:19:55+02:00",
  "meldingsId": "C5E8E429-2B8E-48A9-A9D3-FDAA5F9BE2",
  "rekvisisjonsId": "0322B3E2-B12B-40B6-8940-799C48706123",
  "saksId": "ABC123",
  "fortolkningstekst": "En faglig vurdering av prøveresultatet.",
  "sakskommentar": "Kan eksempelvis inneholde en kommentar om prøvens tilstand.",
  "analyseresultater": [
    {
      "typeAnalyse": "Etanol",
      "erPaavist": false,
      "erAkkreditertMetode": true
    }
  ]
}
